# @author: my@daisg.com
# @date: 2025-10-21
# @version: 0.1
# Copyright (c) 2025 daisg
# SPDX-License-Identifier: GPL-3
# @brief/ Description
database:
  host: "localhost"
  port: 5432
  name: "quant_trading"
  username: "quant_user"
  password: "secure_password"