# @author: my@daisg.com
# @date: 2025-10-21
# @version: 0.1
# Copyright (c) 2025 daisg
# SPDX-License-Identifier: GPL-3
# @brief/ Description
# 日志系统配置
global:
  min_level: "INFO"  # DEBUG, INFO, WARN, ERROR

file_handler:
  enabled: true
  level: "DEBUG"
  log_directory: "logs/"
  max_file_size: "10MB"
  backup_count: 10

console_handler:
  enabled: true  
  level: "INFO"

database_handler:
  enabled: false
  level: "INFO"

# 性能日志配置
performance_logging:
  enabled: true
  interval: 300  # 5分钟
  metrics:
    - "cpu_usage"
    - "memory_usage" 
    - "strategy_performance"
    - "execution_latency"