# @author: my@daisg.com
# @date: 2025-10-21
# @version: 0.1
# Copyright (c) 2025 daisg
# SPDX-License-Identifier: GPL-3
# @brief/ Description
# 风险限制配置
position_limits:
  max_position_per_symbol: 100000  # 单个标的最大头寸
  max_total_position: 1000000     # 总头寸限制
  concentration_limit: 0.1        # 单个标的集中度限制 (10%)

stop_loss:
  fixed_percentage: 0.05          # 固定止损百分比 (5%)
  trailing_percentage: 0.03       # 移动止损百分比 (3%)

drawdown_limits:
  max_drawdown: 0.08              # 最大允许回撤 (8%)
  hard_drawdown_limit: 0.12       # 硬回撤限制 (12%)
  position_reduction_pct: 0.3     # 回撤触发时减仓比例 (30%)

var_limits:
  daily_var_95: -0.02            # 日度95% VaR限制 (-2%)
  weekly_var_95: -0.05           # 周度95% VaR限制 (-5%)

liquidity_limits:
  max_position_to_volume: 0.1    # 头寸/成交量比例限制
  min_liquidity_score: 0.5       # 最小流动性评分